
	var  nav = [];
	nav[0]={
		"carousel":["img/allShop/banner/banner1.png","img/allShop/banner/banner1.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/vedio/img111.png","img/allShop/move/img211.png","img/allShop/travel/img311.png","img/allShop/department/img411.png","img/allShop/city/img511.png","img/allShop/restaurant/img611.png","img/allShop/life/img711.png","img/allShop/education/img811.png"]
			},
		]
	};
	//娱乐影音
	nav[1]={
		"carousel":["img/allShop/banner/banner2.png","img/allShop/banner/banner2.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/vedio/img111.png","img/allShop/vedio/img121.png","img/allShop/vedio/img131.png","img/allShop/vedio/img141.png","img/allShop/vedio/img151.png","img/allShop/vedio/img152.png"]
			},
			{
				"name":"视频",
				"img":["img/allShop/vedio/img111.png","img/allShop/vedio/img112.png","img/allShop/vedio/img113.png"]
			},
			{
				"name":"音乐",
				"img":["img/allShop/vedio/img121.png","img/allShop/vedio/img122.png","img/allShop/vedio/img123.png"]
			},
			{
				"name":"游戏",
				"img":["img/allShop/vedio/img131.png","img/allShop/vedio/img132.png"]
			},
			{
				"name":"休闲娱乐",
				"img":["img/allShop/vedio/img141.png","img/allShop/vedio/img142.png"]
			},
			{
				"name":"知识付费",
				"img":["img/allShop/vedio/img151.png","img/allShop/vedio/img152.png"]
			},
		]
	};
//	"img/allShop/vedio/img152.png"
	//移动社交
	nav[2]={
		"carousel":["img/allShop/banner/banner3.png","img/allShop/banner/banner3.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/move/img211.png","img/allShop/move/img212.png"]
			},
			{
				"name":"社交",
				"img":["img/allShop/move/img211.png"]
			},
			{
				"name":"婚恋",
				"img":["img/allShop/move/img212.png"]
			}
		]
	
	};
	// 票务出行
	nav[3]={
		"carousel":["img/allShop/banner/banner4.png","img/allShop/banner/banner4.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/travel/img311.png","img/allShop/travel/img312.png","img/allShop/travel/img313.png","img/allShop/travel/img314.png","img/allShop/travel/img321.png","img/allShop/travel/img322.png","img/allShop/travel/img331.png","img/allShop/travel/img332.png"]
			},
			{
				"name":"交通出行",
				"img":["img/allShop/travel/img311.png","img/allShop/travel/img312.png","img/allShop/travel/img313.png","img/allShop/travel/img314.png"]
			},
			{
				"name":"酒店住宿",
				"img":["img/allShop/travel/img321.png","img/allShop/travel/img322.png"]
			},
			{
				"name":"旅游出行",
				"img":["img/allShop/travel/img331.png","img/allShop/travel/img332.png"]
			},
		]
	};
	//百货电商
	nav[4]={
		"carousel":["img/allShop/banner/banner5.png","img/allShop/banner/banner5.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/department/img411.png","img/allShop/department/img412.png","img/allShop/department/img421.png","img/allShop/department/img422.png"]
			},
			{
				"name":"综合电商",
				"img":["img/allShop/department/img411.png","img/allShop/department/img412.png"]
			},
			{
				"name":"垂直电商",
				"img":["img/allShop/department/img421.png","img/allShop/department/img422.png"]
			},
		]
	};
	//城市服务
	nav[5]={
		"carousel":["img/allShop/banner/banner6.png","img/allShop/banner/banner6.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/city/img511.png","img/allShop/city/img512.png","img/allShop/city/img521.png","img/allShop/city/img522.png","img/allShop/city/img531.png","img/allShop/city/img532.png","img/allShop/city/img541.png","img/allShop/city/img542.png","img/allShop/city/img551.png","img/allShop/city/img561.png","img/allShop/city/img571.png"]
			},
			{
				"name":"医药体检",
				"img":["img/allShop/city/img511.png","img/allShop/city/img512.png"]
			},
			{
				"name":"快递服务",
				"img":["img/allShop/city/img521.png","img/allShop/city/img522.png"]
			},
			{
				"name":"搬家保洁",
				"img":["img/allShop/city/img531.png","img/allShop/city/img532.png"]
			},
			{
				"name":"美容美甲",
				"img":["img/allShop/city/img541.png","img/allShop/city/img542.png"]
			},
			{
				"name":"手机维修",
				"img":["img/allShop/city/img551.png"]
			},
			{
				"name":"生活服务",
				"img":["img/allShop/city/img561.png"]
			},
			{
				"name":"汽车服务",
				"img":["img/allShop/city/img571.png"]
			},
		]
	};
	//餐饮商超
	nav[6]={
		"carousel":["img/allShop/banner/banner7.png","img/allShop/banner/banner7.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/restaurant/img611.png","img/allShop/restaurant/img612.png","img/allShop/restaurant/img621.png","img/allShop/restaurant/img622.png","img/allShop/restaurant/img631.png","img/allShop/restaurant/img641.png","img/allShop/restaurant/img651.png"]
			},
			{
				"name":"餐饮门店",
				"img":["img/allShop/restaurant/img611.png","img/allShop/restaurant/img612.png"]
			},
			{
				"name":"连锁超市",
				"img":["img/allShop/restaurant/img621.png","img/allShop/restaurant/img622.png"]
			},
			{
				"name":"蛋糕西点",
				"img":["img/allShop/restaurant/img631.png"]
			},
			{
				"name":"休闲饮品",
				"img":["img/allShop/restaurant/img641.png"]
			},
			{
				"name":"小吃零食",
				"img":["img/allShop/restaurant/img651.png"]
			},
		]
	};
	//智能生活
	nav[7]={
		"carousel":["img/allShop/banner/banner8.png","img/allShop/banner/banner8.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/life/img711.png","img/allShop/life/img712.png","img/allShop/life/img721.png","img/allShop/life/img731.png","img/allShop/life/img741.png"]
			},
			{
				"name":"外卖团购",
				"img":["img/allShop/life/img711.png","img/allShop/life/img712.png"]
			},
			{
				"name":"电影购票",
				"img":["img/allShop/life/img721.png"]
			},
			{
				"name":"停车缴费",
				"img":["img/allShop/life/img731.png"]
			},
			{
				"name":"话费充值",
				"img":["img/allShop/life/img741.png"]
			},
		]
	};
	//教育办公
	nav[8]={
		"carousel":["img/allShop/banner/banner9.png","img/allShop/banner/banner9.png"],
		"nav":[
			{
				"name":"全部",
				"img":["img/allShop/education/img811.png","img/allShop/education/img812.png","img/allShop/education/img821.png"]
			},
			{
				"name":"教育",
				"img":["img/allShop/education/img811.png","img/allShop/education/img812.png"]
			},
			{
				"name":"招聘",
				"img":["img/allShop/education/img821.png"]
			}
		]
	};


